#!/usr/bin/env python3
"""
NER-RAKSHA Database Seeding Script

Connects to PostgreSQL using psycopg2, clears existing demo data,
and inserts all entities generated by generate_demo_data.py with
proper PostGIS geometries.
"""

import json
import os
import psycopg2
from psycopg2.extras import DictCursor
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

DB_URL = os.environ.get('DATABASE_URL_SYNC', 'postgresql://postgres:postgres@localhost:5432/ner_raksha')
DEMO_DATA_PATH = Path(__file__).parent.parent / 'data' / 'demo' / 'demo_data.json'

def seed_database():
    if not DEMO_DATA_PATH.exists():
        print(f"Error: Demo data file not found at {DEMO_DATA_PATH}")
        print("Please run generate_demo_data.py first.")
        return

    print("Loading demo data from JSON...")
    with open(DEMO_DATA_PATH, 'r') as f:
        data = json.load(f)

    print(f"Connecting to database: {DB_URL.split('@')[-1]}")
    try:
        conn = psycopg2.connect(DB_URL)
        conn.autocommit = False
        cur = conn.cursor()

        print("1. Clearing existing demo data...")
        tables = [
            'deliveries', 'vehicles', 'incidents', 'terrain', 'weather',
            'road_segments', 'roads', 'districts', 'states', 'data_sources'
        ]
        
        for table in tables:
            try:
                # Assuming is_demo column exists in all these tables or we just clear the table
                # We'll use a try-except to handle cases where is_demo might not exist if they aren't fully migrated yet
                cur.execute(f"DELETE FROM {table} WHERE is_demo = true")
            except psycopg2.errors.UndefinedColumn:
                conn.rollback()
                print(f"  Note: is_demo column not found in {table}, skipping demo clear for this table.")

        print("2. Inserting States...")
        for s in data.get('states', []):
            cur.execute("""
                INSERT INTO states (id, name, code, is_demo)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING
            """, (s['id'], s['name'], s['code'], True))
            
        print("3. Inserting Districts...")
        for d in data.get('districts', []):
            cur.execute("""
                INSERT INTO districts (id, state_id, name, population, is_demo)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING
            """, (d['id'], d['state_id'], d['name'], d['population'], True))

        print("4. Inserting Roads...")
        for r in data.get('roads', []):
            cur.execute("""
                INSERT INTO roads (id, name, road_class, surface, maxspeed_kmh, district_id, is_demo)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING
            """, (r['id'], r['name'], r['road_class'], r['surface'], r['maxspeed_kmh'], r['district_id'], r['is_demo']))

        print("5. Inserting Road Segments...")
        for rs in data.get('road_segments', []):
            coords = rs['geom_coords']
            linestring = "LINESTRING(" + ", ".join([f"{p[0]} {p[1]}" for p in coords]) + ")"
            cur.execute("""
                INSERT INTO road_segments (id, road_id, sequence, length_m, status, risk_score, risk_level, condition, speed_kmh, weather_risk, terrain_risk, incident_risk, historical_risk, is_demo, last_updated, geom)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, ST_GeomFromText(%s, 4326))
                ON CONFLICT (id) DO NOTHING
            """, (rs['id'], rs['road_id'], rs['sequence'], rs['length_m'], rs['status'], rs['risk_score'], rs['risk_level'], rs['condition'], rs['speed_kmh'], rs['weather_risk'], rs['terrain_risk'], rs['incident_risk'], rs['historical_risk'], rs['is_demo'], rs['last_updated'], linestring))

        print("6. Inserting Weather...")
        for w in data.get('weather', []):
            cur.execute("""
                INSERT INTO weather (district_id, observed_at, rainfall_mm, temperature_c, humidity_pct, wind_speed_kmh, source, is_demo)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """, (w['district_id'], w['observed_at'], w['rainfall_mm'], w['temperature_c'], w['humidity_pct'], w['wind_speed_kmh'], w['source'], w['is_demo']))

        print("7. Inserting Terrain...")
        for t in data.get('terrain', []):
            cur.execute("""
                INSERT INTO terrain (district_id, elevation_m, slope_pct, terrain_class, source, is_demo)
                VALUES (%s, %s, %s, %s, %s, %s)
            """, (t['district_id'], t['elevation_m'], t['slope_pct'], t['terrain_class'], t['source'], True))

        print("8. Inserting Incidents...")
        for inc in data.get('incidents', []):
            cur.execute("""
                INSERT INTO incidents (id, type, severity, title, description, status, reporter_name, source, is_demo, created_at, geom)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, ST_SetSRID(ST_MakePoint(%s, %s), 4326))
            """, (inc['id'], inc['type'], inc['severity'], inc['title'], inc['desc'], inc['status'], inc['reporter_name'], inc['source'], inc['is_demo'], inc['created_at'], inc['lon'], inc['lat']))

        print("9. Inserting Vehicles...")
        for v in data.get('vehicles', []):
            cur.execute("""
                INSERT INTO vehicles (id, name, type, cargo, priority, speed_kmh, status, is_demo, is_simulated, current_position)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, ST_SetSRID(ST_MakePoint(%s, %s), 4326))
                ON CONFLICT (id) DO NOTHING
            """, (v['id'], v['name'], v['type'], v['cargo'], v['priority'], v['speed_kmh'], v['status'], v['is_demo'], v['is_simulated'], v['lon'], v['lat']))

        print("10. Inserting Deliveries...")
        for d in data.get('deliveries', []):
            cur.execute("""
                INSERT INTO deliveries (id, vehicle_id, cargo, priority, origin_name, destination_name, status, scheduled_arrival, estimated_arrival, is_demo, origin, destination)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, ST_SetSRID(ST_MakePoint(%s, %s), 4326), ST_SetSRID(ST_MakePoint(%s, %s), 4326))
            """, (d['id'], d['vehicle_id'], d['cargo'], d['priority'], d['origin_name'], d['destination_name'], d['status'], d['scheduled_arrival'], d['estimated_arrival'], d['is_demo'], d['origin'][0], d['origin'][1], d['destination'][0], d['destination'][1]))

        print("11. Inserting Data Sources...")
        for ds in data.get('data_sources', []):
            cur.execute("""
                INSERT INTO data_sources (name, dataset, url, status, mode, coverage, refresh_interval, notes, is_demo)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """, (ds['name'], ds['dataset'], ds['url'], ds['status'], ds['mode'], ds['coverage'], ds['refresh_interval'], ds['notes'], True))

        conn.commit()
        print("\n✅ Database seeding completed successfully!")
        
        cur.execute("SELECT count(*) FROM road_segments;")
        print(f"Road segments inserted: {cur.fetchone()[0]}")
        cur.execute("SELECT count(*) FROM incidents;")
        print(f"Incidents inserted: {cur.fetchone()[0]}")
        
    except Exception as e:
        if 'conn' in locals():
            conn.rollback()
        print(f"\n❌ Error during seeding: {e}")
    finally:
        if 'cur' in locals(): cur.close()
        if 'conn' in locals(): conn.close()

if __name__ == '__main__':
    seed_database()
